= キッチンタイマー仕様書

== システム概要
. タイマーの分と秒はLCDで表示する。
. 分エリアは0から99まで表示できる。
. 秒エリアは0から59まで表示できる。
. 99分59秒に設定された後、分・秒いずれかのボタンが押された場合、0分0秒にリセットされる。
. タイマー動作中にスタートストップボタンが押されたとき、タイマーのカウントはそのままタイマーセット状態にする。
. タイマーセット状態でスタートストップボタンが押されたとき、タイマーを開始する。
. タイマー動作中に0分0秒までカウントダウンした際に、LCD表示を点滅させ、アラームを鳴らす。
. アラームが鳴ってから30秒経過したとき、アラームを停止する。
. アラームが鳴ってからスタートストップボタンが押されたとき、アラームを停止する。
. アラームが停止したとき、最後にセットされた時間を再表示する。

== ユースケース図
[plantuml]
----
'usecase diagram
left to right direction
actor ユーザ
rectangle キッチンタイマー{
    usecase 時間を計る
    usecase タイマーをセットする
    usecase タイマーを動作する
    usecase アラームを鳴らす
}
ユーザ --> (時間を計る)
(時間を計る) ..> (タイマーをセットする): include
(時間を計る) ..> (タイマーを動作する): include
(タイマーを動作する) .> (アラームを鳴らす): include
----

== ユースケース記述
* ユースケース名：時間を計る。
* 基本フロー
. ユーザは"分ボタン"と"秒ボタン"を押す。
. システムはタイマーをセットする。
. ユーザはスタートストップボタンを押す。
. システムはカウントダウンを開始する。
. システムはアラームを鳴らす。
. ユーザはアラームを停止させる。
. システムは最後にセットされた時間を再表示する。
* 代替フロー
* ユースケース名：タイマーをセットする
* 基本フロー
. ユーザは"分ボタン"と"秒ボタン"を押す。
. システムは押されたボタンに応じて分数と秒数を加算する。
. システムは押されたボタンに対応した値をLCDに表示する
* 代替フロー
. LCDの分エリアの表示が'99'のとき、"分ボタン"が押されたとき、LCDの分エリアの値を0へ変更する。
. LCDの表示が'99分59秒'のとき、"分ボタン"か"秒ボタン"が押されたとき、LCDの値を0分0秒へ変更する。
* ユースケース名：タイマーを動作する
* 基本フロー
. システムはセットされた時間から"0分0秒"までカウントダウンをする。
. システムはLCDを点滅させる。
. システムはアラームを鳴らす。
* 代替フロー
. システムはカウントダウンの最中に"スタートストップボタン"が押されたときカウントダウンを停止する。
* ユースケース名：アラームを鳴らす
* 基本フロー
. システムはアラームを鳴らす。
. ユーザは"スタートストップボタン"を押す。
. システムはアラームを停止する。
. システムは最後にセットされた時間を再表示する
* 代替フロー
. システムはアラームが30秒間鳴り続けたとき、アラームを停止する。

== 状態遷移図
[plantuml]
----
'statemachine diagram
state 0分0秒表示中
state タイマーセット中
state カウントダウン中
state アラーム動作中

[*] -> 0分0秒表示中
0分0秒表示中 -> 0分0秒表示中: スタートストップボタン押下
0分0秒表示中 -> タイマーセット中: 分ボタンまたは秒ボタン押下
タイマーセット中 --> 0分0秒表示中: "99分59秒"表示中に分ボタンまたは秒ボタン押下
タイマーセット中 -> タイマーセット中: "99分59秒"以外表示中に分ボタンまたは秒ボタン押下
タイマーセット中 --> カウントダウン中: スタートストップボタン押下
カウントダウン中 --> タイマーセット中: スタートストップボタン押下
カウントダウン中 -> アラーム動作中: 0分0秒までカウントダウン完了
アラーム動作中 -> タイマーセット中: スタートストップボタン押下または30秒経過
----

== シーケンス図
[plantuml]
----
'sequence diagram
actor ユーザ
ユーザ -> ボタン: スタートストップボタン押下
ボタン -> タイマー: タイマー起動
タイマー -> タイマー: カウントダウン開始
タイマー -> LCD: 残り時間表示
LCD --> ユーザ: 残り時間表示
タイマー -> タイマー: カウントダウン終了
タイマー -> アラーム: アラーム起動
アラーム --> ユーザ: アラーム鳴動
ユーザ -> ボタン: スタートストップボタン押下
ボタン --> アラーム: アラーム停止
アラーム --> ユーザ: アラーム停止
----

== クラス図
.クラス図
|===
|クラス名|責務
|設定時間|設定時間の変更、保持
|LCD|設定時間の表示
|タイマー|設定時間からカウントダウン
|アラーム|アラームの鳴動、停止
|===